import { createRouter, createWebHistory } from 'vue-router'
import type { RouteRecordRaw } from 'vue-router'

const routes: RouteRecordRaw[] = [
  { path: '/', component: () => import('./pages/Home.vue') },
  { path: '/docs', component: () => import('./pages/DocsPage.vue') },
  { path: '/basic', component: () => import('./pages/BasicPage.vue') },
  { path: '/grid-events', component: () => import('./pages/GridEventsPage.vue') },
  { path: '/i18n/en', component: () => import('./pages/I18nEnPage.vue') },
  { path: '/i18n/es', component: () => import('./pages/I18nEsPage.vue') },
  { path: '/i18n/custom', component: () => import('./pages/I18nCustomPage.vue') },
  { path: '/intl-service', component: () => import('./pages/IntlServicePage.vue') },
  { path: '/cards', component: () => import('./pages/ResponsiveCardsPage.vue') },
  { path: '/setup', component: () => import('./pages/SetupGuidePage.vue') },
  { path: '/virtual', component: () => import('./pages/VirtualPage.vue') },
  { path: '/virtualization', component: () => import('./pages/VirtualizationPage.vue') },
  { path: '/scrollable-virtual', component: () => import('./pages/ScrollableVirtualPage.vue') },
  { path: '/scrollable-endless', component: () => import('./pages/ScrollableEndlessPage.vue') },
  { path: '/sortable-props', component: () => import('./pages/SortablePropsPage.vue') },
  { path: '/aggregates', component: () => import('./pages/AggregatesPage.vue') },
  { path: '/server', component: () => import('./pages/ServerSidePage.vue') },
  { path: '/grouping', component: () => import('./pages/GroupingPage.vue') },
  { path: '/grouping-basics', component: () => import('./pages/GroupingBasicsPage.vue') },
  { path: '/table-only', component: () => import('./pages/TableOnlyPage.vue') },
  { path: '/hide-header', component: () => import('./pages/HideHeaderPage.vue') },
  { path: '/pagination', component: () => import('./pages/PaginationShowcase.vue') },
  { path: '/pagination/standalone', component: () => import('./pages/PaginationStandalonePage.vue') },
  { path: '/pager/advanced', component: () => import('./pages/PagerAdvancedPage.vue') },
  { path: '/locked', component: () => import('./pages/LockedColumnsPage.vue') },
  { path: '/adaptive-height', component: () => import('./pages/AdaptiveHeightSlotsPage.vue') },
  { path: '/data-binding', component: () => import('./pages/DataBindingPage.vue') },
  { path: '/data/local', component: () => import('./pages/DataLocalPage.vue') },
  { path: '/data/rest', component: () => import('./pages/DataRestPage.vue') },
  { path: '/data/graphql', component: () => import('./pages/DataGraphQLPage.vue') },
  { path: '/data/websocket', component: () => import('./pages/DataWebSocketPage.vue') },
  { path: '/data/offline', component: () => import('./pages/DataOfflinePage.vue') },
  { path: '/data/datasource', component: () => import('./pages/DataSourcePage.vue') },
  { path: '/data/gantt-datasource', component: () => import('./pages/GanttDataSourcePage.vue') },
  { path: '/data/gantt-dependency-datasource', component: () => import('./pages/GanttDependencyDataSourcePage.vue') },
  { path: '/data/hierarchical-datasource', component: () => import('./pages/HierarchicalDataSourcePage.vue') },
  { path: '/data/pivot-datasource', component: () => import('./pages/PivotDataSourcePage.vue') },
  { path: '/data/scheduler-datasource', component: () => import('./pages/SchedulerDataSourcePage.vue') },
  { path: '/data/treelist-datasource', component: () => import('./pages/TreeListDataSourcePage.vue') },
  { path: '/persisted', component: () => import('./pages/PersistedStatePage.vue') },
  { path: '/custom-cells', component: () => import('./pages/CustomCellsPage.vue') },
  { path: '/styled-table', component: () => import('./pages/StyledTablePage.vue') },
  { path: '/gallery', component: () => import('./pages/ImageGalleryPage.vue') },
  { path: '/editing', component: () => import('./pages/EditingPage.vue') },
  { path: '/filtering', component: () => import('./pages/FilteringPage.vue') },
  { path: '/keyboard-navigation', component: () => import('./pages/KeyboardNavigationPage.vue') },
  { path: '/paging', component: () => import('./pages/PagingPage.vue') },
  { path: '/pagination-url', component: () => import('./pages/PaginationUrlPage.vue') },
  { path: '/sorting', component: () => import('./pages/SortingPage.vue') },
  { path: '/rtl', component: () => import('./pages/RTSPage.vue') },
  { path: '/selection', component: () => import('./pages/SelectionPage.vue') },
  { path: '/copy', component: () => import('./pages/CopyPage.vue') },
  { path: '/column-menu', component: () => import('./pages/ColumnMenuPage.vue') },
  { path: '/excel-export', component: () => import('./pages/ExcelExportPage.vue') },
  { path: '/csv-docx-export', component: () => import('./pages/CsvDocxExportPage.vue') },
  { path: '/filterable-props', component: () => import('./pages/FilterablePropsPage.vue') },
  { path: '/grid-column', component: () => import('./pages/GridColumnPage.vue') },
  { path: '/templates', component: () => import('./pages/TemplatesPage.vue') },
  { path: '/persist-state', component: () => import('./pages/PersistStatePage.vue') },
  { path: '/custom-commands', component: () => import('./pages/CustomCommandsPage.vue') },
  { path: '/foreign-key-columns', component: () => import('./pages/ForeignKeyColumnsPage.vue') },
  { path: '/pinned-columns', component: () => import('./pages/PinnedColumnsPage.vue') },
  { path: '/multi-column-headers', component: () => import('./pages/MultiColumnHeadersPage.vue') },
  { path: '/reordering', component: () => import('./pages/ReorderingPage.vue') },
  { path: '/resizing', component: () => import('./pages/ResizingPage.vue') },
  { path: '/groupable-props', component: () => import('./pages/GroupablePropsPage.vue') },
  { path: '/messages-props', component: () => import('./pages/MessagesPropsPage.vue') },
  { path: '/no-records-props', component: () => import('./pages/NoRecordsPropsPage.vue') },
  { path: '/pageable-props', component: () => import('./pages/PageablePropsPage.vue') },
  { path: '/pdf-export', component: () => import('./pages/PdfExportPage.vue') },
  { path: '/images', component: () => import('./pages/ImagesPage.vue') },
  { path: '/row-height', component: () => import('./pages/RowHeightPage.vue') },
  { path: '/cell-row-column-styling', component: () => import('./pages/CellRowColumnStylingPage.vue') },
  { path: '/styling-props', component: () => import('./pages/StylingPropsPage.vue') },
  { path: '/grid-styles', component: () => import('./pages/GridStylesPage.vue') },
  { path: '/charts-in-grid', component: () => import('./pages/ChartsInGridPage.vue') },
  { path: '/complete-example', component: () => import('./pages/CompleteExamplePage.vue') },
  { path: '/listview', component: () => import('./pages/ListViewPage.vue') },
]

export const router = createRouter({
  history: createWebHistory('/pantanal-grid/'),
  routes,
})
